name: mutfak21
favicon: null
layout_spectrum: 0.6441937424242496
typography_spectrum: 0.01508119492791593
title: mutfak21
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#12150c'
    - '#3d4142'
    - '#982f28'
    - '#c75640'
    - '#d5836b'
  brandStrength: 0.75
  lightness: 0.3125
  saturation: 0.625
  rhythmicContrast: 0.25
purpose: []
