name: mutfak21
favicon: null
layout_spectrum: 0.24277
typography_spectrum: 0.59151
title: mutfak21
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#232427'
    - '#697c72'
    - '#89503d'
    - '#ba8a71'
  brandStrength: 0.5
  lightness: 0.875
  saturation: 1
  rhythmicContrast: 0.25
purpose: []
