name: mutfak21
favicon: null
layout_spectrum: 0.6441937424242496
typography_spectrum: 0.01508119492791593
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0.7514333571307361
  lightness: 0.4469149699434638
  saturation: 0.38573351479135454
  rhythmicContrast: 0.2628024162258953
purpose: []
